server:
  port: 8071
spring:
  application:
    name: config-server
  profiles:
    active: native
    #active: git
  cloud:
    config:
      server:
        native:
          # Busca de configurações nos arquivos dentro do diretório config de resources
          search-locations: "classpath:/config"
          # Busca de configurações em um diretório específico da máquina
          # search-locations: file:///home/ian/Documents/Projetos/Configurations
        # Busca de configurações localizadas em um repositório GIT.
       #git:
          #uri: https://github.com/Microservices-course
          #default-label: config
          #timeout: 5
          #clone-on-start: true
          #force-pull: true
